<?php

    namespace Database\Seeders;

    use App\Enums\DesignStyle;
    use App\Enums\PageOrientation;
    use App\Enums\ThermalSize;
    use Illuminate\Database\Seeder;
    use Illuminate\Support\Facades\DB;

    class PrinterTemplatesSeeder extends Seeder
    {

        public function run() : void
        {
            if ( DB::table( 'print_templates' )->exists() ) {
                return;
            }
            $templates = [
                [
                    'name'             => "Main POS Receipt (58mm)" , 'type' => 1 , 'design' => DesignStyle::MODERN , 'is_default' => TRUE ,
                    'store_name'       => "Smart Duuka Central" , 'address' => "Kampala Road, Kampala, Uganda" , 'phone' => "+256 700 000000" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 50 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "Thank you for shopping at Smart Duuka!" , 'show_barcode' => TRUE , 'terms' => "Retain receipt for returns within 7 days." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => FALSE , 'text_bold' => FALSE , 'large_text' => FALSE , 'color_theme' => '#ea580c'
                ] ,
                [
                    'name'             => "Wholesale B2B Invoice" , 'type' => 2 , 'design' => DesignStyle::MODERN , 'is_default' => FALSE ,
                    'store_name'       => "Smart Duuka Wholesale" , 'address' => "Industrial Area, Kampala, Uganda" , 'phone' => "+256 750 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 80 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "Payment due within 30 days via Bank Transfer." , 'show_barcode' => FALSE , 'terms' => "Goods once sold in good condition are not returnable." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => TRUE , 'text_bold' => FALSE , 'large_text' => FALSE , 'color_theme' => '#1e3a8a'
                ] ,
                [
                    'name'             => "Electronic Repairs Ticket" , 'type' => 3 , 'design' => DesignStyle::MINIMAL , 'is_default' => FALSE ,
                    'store_name'       => "Smart Duuka Repairs" , 'address' => "Ground Floor, Tech Mall" , 'phone' => "+256 770 111222" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => FALSE , 'logo_size' => 0 , 'show_quantity' => TRUE , 'show_price' => FALSE , 'show_tax' => FALSE ,
                    'footer_message'   => "Bring this ticket to collect your device." , 'show_barcode' => TRUE , 'terms' => "Not liable for data loss." ,
                    'thermal_size'     => ThermalSize::EIGHTY_MM->value , 'has_borders' => TRUE , 'text_bold' => TRUE , 'large_text' => TRUE , 'color_theme' => '#000000'
                ] ,
                [
                    'name'             => "Weekly Sales Report" , 'type' => 4 , 'design' => DesignStyle::BORDERED_TABLE , 'is_default' => FALSE ,
                    'store_name'       => "Smart Duuka Central" , 'address' => "Kampala Road, Kampala" , 'phone' => "+256 700 000000" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 40 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "Generated automatically by the POS System." , 'show_barcode' => FALSE , 'terms' => "Internal Use Only" ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => TRUE , 'text_bold' => TRUE , 'large_text' => FALSE , 'color_theme' => '#0f766e'
                ] ,
                [
                    'name'             => "Modern Orange Performance" , 'type' => 4 , 'design' => DesignStyle::MODERN , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 45 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "Generated by Smart Serve POS - End of Day" , 'show_barcode' => FALSE , 'terms' => "Strictly for internal management review." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => FALSE , 'text_bold' => FALSE , 'large_text' => FALSE , 'color_theme' => '#f97316'
                ] ,
                [
                    'name'             => "Corporate Blue Overview" , 'type' => 4 , 'design' => DesignStyle::MODERN , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => FALSE , 'logo_size' => 0 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "Financial metrics are subject to audit." , 'show_barcode' => FALSE , 'terms' => "Confidential Financial Document." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => FALSE , 'text_bold' => FALSE , 'large_text' => TRUE , 'color_theme' => '#1e3a8a'
                ] ,
                [
                    'name'             => "Minimalist Grayscale" , 'type' => 4 , 'design' => DesignStyle::BOLD_COMPACT , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 60 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => FALSE ,
                    'footer_message'   => "Monthly Performance Review" , 'show_barcode' => TRUE , 'terms' => "For Managerial Use Only." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => TRUE , 'text_bold' => FALSE , 'large_text' => FALSE , 'color_theme' => '#000000'
                ] ,
                [
                    'name'             => "Emerald Eco Summary" , 'type' => 4 , 'design' => DesignStyle::ECO_SAVER , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 50 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "Eco-Friendly Digital Export" , 'show_barcode' => FALSE , 'terms' => "Generated on Smart Serve." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => FALSE , 'text_bold' => FALSE , 'large_text' => FALSE , 'color_theme' => '#059669'
                ] ,
                [
                    'name'             => "Crimson Bold Analysis" , 'type' => 4 , 'design' => DesignStyle::PROFESSIONAL_BLUE , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => FALSE , 'logo_size' => 0 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "Executive Summary Report" , 'show_barcode' => FALSE , 'terms' => "Do not distribute externally." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => FALSE , 'text_bold' => TRUE , 'large_text' => TRUE , 'color_theme' => '#991b1b'
                ] ,
                [
                    'name'             => "Indigo Elegant Flow" , 'type' => 4 , 'design' => DesignStyle::GRID_SYSTEM , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 40 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => FALSE ,
                    'footer_message'   => "Automated System Export" , 'show_barcode' => TRUE , 'terms' => "Valid for the month of July 2024." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => FALSE , 'text_bold' => FALSE , 'large_text' => FALSE , 'color_theme' => '#4f46e5'
                ] ,
                [
                    'name'             => "Detailed Analytics Dash" , 'type' => 4 , 'design' => DesignStyle::HEADER_FOCUS , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => FALSE , 'logo_size' => 0 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "Comprehensive Breakdown" , 'show_barcode' => TRUE , 'terms' => "Contains sensitive pricing data." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => FALSE , 'text_bold' => FALSE , 'large_text' => FALSE , 'color_theme' => '#134e4a'
                ] ,
                [
                    'name'             => "Slate High-Density Ledger" , 'type' => 4 , 'design' => DesignStyle::BORDERED_TABLE , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 35 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "POS Export Database Sync" , 'show_barcode' => FALSE , 'terms' => "ID: OSB-2024-07" ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => TRUE , 'text_bold' => TRUE , 'large_text' => FALSE , 'color_theme' => '#334155'
                ] ,
                [
                    'name'             => "Rose Sales Vibe" , 'type' => 4 , 'design' => DesignStyle::ELEGANT_SERIF , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => FALSE , 'logo_size' => 0 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => FALSE ,
                    'footer_message'   => "Great job this month! Keep it up." , 'show_barcode' => FALSE , 'terms' => "Team Performance Document" ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => FALSE , 'text_bold' => TRUE , 'large_text' => TRUE , 'color_theme' => '#e11d48'
                ] ,
                [
                    'name'             => "Amber Classic Grid" , 'type' => 4 , 'design' => DesignStyle::INDUSTRIAL_MONO , 'is_default' => FALSE ,
                    'store_name'       => "The Orange Spoon Bistro" , 'address' => "Kampala, Uganda" , 'phone' => "+256 700 123456" ,
                    'page_orientation' => PageOrientation::Portrait->value ,
                    'show_logo'        => TRUE , 'logo_size' => 55 , 'show_quantity' => TRUE , 'show_price' => TRUE , 'show_tax' => TRUE ,
                    'footer_message'   => "End of month structured grid export." , 'show_barcode' => TRUE , 'terms' => "All figures in UGX." ,
                    'thermal_size'     => ThermalSize::FIFTY_EIGHT_MM->value , 'has_borders' => TRUE , 'text_bold' => FALSE , 'large_text' => FALSE , 'color_theme' => '#d97706'
                ]
            ];

            DB::table( 'print_templates' )->insert( $templates );
        }
    }
